---
abstract: 'A lightweight SQL helper for DBI'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::chdir: '0'
  Test::Database: '0'
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.08'
  File::ShareDir::Install: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-ThinSQL
no_index:
  directory:
    - t
    - inc
  package:
    - DBIx::ThinSQL::Driver
    - DBIx::ThinSQL::Driver::Pg
    - DBIx::ThinSQL::Driver::SQLite
    - DBIx::ThinSQL::bind_value
    - DBIx::ThinSQL::case
    - DBIx::ThinSQL::db
    - DBIx::ThinSQL::expr
    - DBIx::ThinSQL::list
    - DBIx::ThinSQL::query
    - DBIx::ThinSQL::quote_identifier
    - DBIx::ThinSQL::quote_value
    - DBIx::ThinSQL::st
    - DBIx::ThinSQL::table
    - DBIx::ThinSQL::values
requires:
  DBI: '0'
  Exporter::Tidy: '0'
  File::ShareDir: '1.116'
  Log::Any: '0'
  Path::Tiny: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-DBIx-ThinSQL.git
version: v0.0.50
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
